from .data_loader import load_challenges, load_solutions, load_task_pairs
from .task import Task
from .grid import Grid
from .generator_primitives import (
    Object,
    RayStep,
    Region,
    background_color,
    background_regions,
    bbox_of_mask,
    best_candidate,
    blank_grid,
    clone_grid,
    complete_by_symmetry,
    components4,
    crop_bbox,
    detect_period,
    enclosed_regions,
    fill_periodic_holes,
    in_bounds,
    mask_color,
    move_content_to_edge,
    nonzero_colors,
    overlay,
    raycast,
    select_color_by_rank,
    select_object,
    shape,
    slide_layer,
    split_by_separators,
    take_panel,
    translate_layer,
    unique_or_reject,
    zip_panels,
)
